Repository SAP-samples/fundamental-ngx-sample-apps, pull requests merged in 2020-06, with the labels that each got.

#34 chore: add migration to angular 9 and change to fd layout grid
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/components/contracts/create-contract-modal/create-contract-modal.component.html
  src/styles.css
  src/styles.scss
Labels: bug, dependencies, documentation

#76 add luigi option to remove header and side nav
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/theme-selector/theme-selector.component.html
  src/app/components/theme-selector/theme-selector.component.scss
  src/app/components/theme-selector/theme-selector.component.ts
  src/app/services/luigi-ui/luigi-ui.service.spec.ts
  src/app/services/luigi-ui/luigi-ui.service.ts
Labels: enhancement

#78 fix: add query params for luigi
  src/app/app.component.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/services/auth/auth.service.ts
  src/app/services/luigi-ui/luigi-ui.service.ts
Labels: documentation, enhancement

#79 feat: add theming to app
  src/app/app.component.scss
  src/app/components/contracts/contracts.component.html
  src/app/components/contracts/contracts.component.scss
  src/app/components/products/products.component.html
  src/app/components/products/products.component.scss
Labels: theme

#80 feat: add compact mode globally
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/contracts/contracts.component.html
  src/app/components/contracts/contracts.component.ts
  src/app/components/contracts/create-contract-modal/create-contract-modal.component.html
  src/app/components/contracts/create-contract-modal/create-contract-modal.component.ts
  src/app/components/products/create-product-modal/create-product-modal-detailed/create-product-modal-detailed.component.html
  src/app/components/products/create-product-modal/create-product-modal-detailed/create-product-modal-detailed.component.ts
  src/app/components/products/create-product-modal/create-product-modal.component.html
  src/app/components/products/create-product-modal/create-product-modal.component.ts
  src/app/components/products/products.component.html
  src/app/components/products/products.component.ts
  src/app/components/theme-selector/theme-selector.component.html
  src/app/components/theme-selector/theme-selector.component.ts
  src/app/services/compact/compact.service.spec.ts
  src/app/services/compact/compact.service.ts
  src/styles.css
Labels: documentation, enhancement

#88 feat: add services for data
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/components/contracts/contracts.component.html
  src/app/components/contracts/contracts.component.scss
  src/app/components/contracts/contracts.component.ts
  src/app/components/contracts/create-contract-modal/create-contract-modal.component.html
  src/app/components/contracts/create-contract-modal/create-contract-modal.component.ts
  src/app/components/dashboard/dashboard.component.html
  src/app/components/dashboard/dashboard.component.ts
  src/app/components/products/create-product-modal/create-product-modal.component.html
  src/app/components/products/create-product-modal/create-product-modal.component.ts
  src/app/components/products/products.component.html
  src/app/components/products/products.component.scss
  src/app/components/products/products.component.ts
  src/app/pipes/snake-case.pipe.spec.ts
  src/app/pipes/snake-case.pipe.ts
  src/app/services/compact/compact.service.ts
  src/app/services/contract-page/contract-page.service.spec.ts
  src/app/services/contract-page/contract-page.service.ts
  src/app/services/product-page/product-page.service.spec.ts
  src/app/services/product-page/product-page.service.ts
  src/app/services/product-switch/product-switch.service.spec.ts
  src/app/services/product-switch/product-switch.service.ts
  src/app/services/products/products.service.ts
  src/app/services/side-navigation/side-navigation.model.ts
  src/app/services/side-navigation/side-navigation.service.spec.ts
  src/app/services/side-navigation/side-navigation.service.ts
Labels: enhancement

#89 fix: add fields to edit product dialog
  src/app/components/products/products.component.scss
  src/app/components/products/products.component.ts
Labels: bug

#90 chore: angular 10
  .browserslistrc
  angular.json
  package-lock.json
  package.json
  tsconfig.json
  tslint.json
Labels: dependencies

#93 feat: add client side authenitcation
  src/app/app.component.html
  src/app/components/confirm-modal/confirm-modal.component.html
  src/app/components/confirm-modal/confirm-modal.component.ts
  src/app/components/contracts/contracts.component.ts
  src/app/components/products/products.component.html
  src/app/components/products/products.component.ts
  src/app/services/products/products.service.ts
  src/app/shared/notification-confirmation/notification-confirmation.component.html
  src/app/shared/notification-confirmation/notification-confirmation.component.ts
Labels: enhancement

#94 feat: add update functionality
  src/app/app.module.ts
  src/app/components/contracts/contracts.component.html
  src/app/components/contracts/contracts.component.ts
  src/app/components/contracts/create-contract-modal/create-contract-modal.component.ts
  src/app/components/products/create-product-modal/create-product-modal.component.ts
  src/app/components/products/products.component.html
  src/app/components/products/products.component.ts
  src/app/pipes/snake-case/snake-case.pipe.spec.ts
  src/app/pipes/snake-case/snake-case.pipe.ts
  src/app/services/contracts/contracts.service.ts
  src/app/services/products/products.service.ts
  src/app/shared/notification-confirmation/notification-confirmation.component.html
  src/app/shared/notification-confirmation/notification-confirmation.component.ts
Labels: enhancement
